USE [master]
GO

/****** Object:  Database [UST.Inclusione]    Script Date: 25/02/2022 14:47:28 ******/
CREATE DATABASE [UST.Inclusione]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UST.Inclusione', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UST.Inclusione.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [FileType] CONTAINS FILESTREAM  DEFAULT
( NAME = N'FileType', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FileType' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'UST.Inclusione_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UST.Inclusione_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UST.Inclusione].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UST.Inclusione] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UST.Inclusione] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UST.Inclusione] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UST.Inclusione] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UST.Inclusione] SET ARITHABORT OFF 
GO

ALTER DATABASE [UST.Inclusione] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UST.Inclusione] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UST.Inclusione] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UST.Inclusione] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UST.Inclusione] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UST.Inclusione] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UST.Inclusione] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UST.Inclusione] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UST.Inclusione] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UST.Inclusione] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UST.Inclusione] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UST.Inclusione] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UST.Inclusione] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UST.Inclusione] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UST.Inclusione] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UST.Inclusione] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UST.Inclusione] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UST.Inclusione] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UST.Inclusione] SET  MULTI_USER 
GO

ALTER DATABASE [UST.Inclusione] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UST.Inclusione] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UST.Inclusione] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UST.Inclusione] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UST.Inclusione] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UST.Inclusione] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UST.Inclusione] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UST.Inclusione] SET  READ_WRITE 
GO

